# Generated by Django 4.2.20 on 2026-06-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Capacidad',
                'verbose_name_plural': 'Capacidades',
                'permissions': [('ciudadano_ver', 'Ver ciudadanos y legajos'), ('ciudadano_crear', 'Crear ciudadanos'), ('ciudadano_editar', 'Editar ciudadanos'), ('ciudadano_eliminar', 'Eliminar ciudadanos'), ('ciudadano_sensible', 'Ver datos sensibles'), ('programa_ver', 'Ver programas'), ('programa_operar', 'Operar programas'), ('programa_configurar', 'Configurar programas'), ('relevamiento_ver', 'Ver relevamientos'), ('relevamiento_gestionar', 'Gestionar relevamientos'), ('conversacion_operar', 'Operar conversaciones'), ('conversacion_configurar', 'Configurar conversaciones'), ('conversacion_metricas', 'Ver métricas de conversaciones'), ('dashboard_ver', 'Ver dashboard'), ('reporte_ver', 'Ver reportes'), ('config_ver', 'Ver configuración'), ('config_administrar', 'Administrar configuración'), ('institucion_ver', 'Ver instituciones'), ('institucion_administrar', 'Administrar instituciones'), ('usuario_administrar', 'Administrar usuarios'), ('rol_administrar', 'Administrar roles')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rol',
        ),
        migrations.CreateModel(
            name='RolMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('Backoffice', 'Backoffice'), ('Institución', 'Institución'), ('Portal', 'Portal'), ('Sistema', 'Sistema')], default='Backoffice', max_length=20, verbose_name='Categoría')),
                ('protegido', models.BooleanField(default=False, verbose_name='Protegido')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='auth.group', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Metadato de rol',
                'verbose_name_plural': 'Metadatos de roles',
            },
        ),
    ]
