# Generated by Django 4.2.20 on 2026-06-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
        ('users', '0002_capacidad_remove_profile_rol_rolmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolmeta',
            name='programa',
            field=models.ForeignKey(blank=True, help_text="Solo para roles de categoría 'Programa': acota el rol a ese programa.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_meta', to='programas.programa', verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='rolmeta',
            name='categoria',
            field=models.CharField(choices=[('Backoffice', 'Backoffice'), ('Institución', 'Institución'), ('Portal', 'Portal'), ('Sistema', 'Sistema'), ('Programa', 'Programa')], default='Backoffice', max_length=20, verbose_name='Categoría'),
        ),
    ]
