# Generated by Django 4.2.20 on 2026-06-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rolmeta_programa_alter_rolmeta_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacidad',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ciudadano_ver', 'Ver ciudadanos y legajos'), ('ciudadano_crear', 'Crear ciudadanos'), ('ciudadano_editar', 'Editar ciudadanos'), ('ciudadano_eliminar', 'Eliminar ciudadanos'), ('ciudadano_sensible', 'Ver datos sensibles'), ('programa_ver', 'Ver programas'), ('programa_operar', 'Operar programas'), ('programa_configurar', 'Configurar programas'), ('relevamiento_ver', 'Ver relevamientos'), ('relevamiento_gestionar', 'Gestionar relevamientos'), ('becas_configurar', 'Configurar Becas (segmentos, cupos, requisitos, preguntas, coordinadores)'), ('becas_relevamientos', 'Gestionar relevamientos de Becas'), ('becas_revisar', 'Revisar formularios de Becas (aprobar/rechazar)'), ('becas_campo', 'Operar la app de campo de Becas (territorial)'), ('conversacion_operar', 'Operar conversaciones'), ('conversacion_configurar', 'Configurar conversaciones'), ('conversacion_metricas', 'Ver métricas de conversaciones'), ('dashboard_ver', 'Ver dashboard'), ('reporte_ver', 'Ver reportes'), ('config_ver', 'Ver configuración'), ('config_administrar', 'Administrar configuración'), ('institucion_ver', 'Ver instituciones'), ('institucion_administrar', 'Administrar instituciones'), ('usuario_administrar', 'Administrar usuarios'), ('rol_administrar', 'Administrar roles')], 'verbose_name': 'Capacidad', 'verbose_name_plural': 'Capacidades'},
        ),
    ]
