# Generated by Django 4.2.30 on 2026-07-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rolmeta_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacidad',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ciudadano_ver', 'Ver ciudadanos y legajos'), ('ciudadano_crear', 'Crear ciudadanos'), ('ciudadano_editar', 'Editar ciudadanos'), ('ciudadano_eliminar', 'Eliminar ciudadanos'), ('ciudadano_sensible', 'Ver datos sensibles'), ('programa_ver', 'Ver programas'), ('programa_operar', 'Operar programas'), ('programa_configurar', 'Configurar programas'), ('relevamiento_ver', 'Ver relevamientos'), ('relevamiento_gestionar', 'Gestionar relevamientos'), ('becas_programa_administrar', 'Administrar el programa Becas (acceso total, asigna coordinadores)'), ('becas_segmento_ver', 'Ver segmentos'), ('becas_segmento_crear', 'Crear segmentos'), ('becas_segmento_editar', 'Editar segmentos (incluye activar/desactivar)'), ('becas_subsegmento_ver', 'Ver subsegmentos'), ('becas_subsegmento_crear', 'Crear subsegmentos'), ('becas_subsegmento_editar', 'Editar subsegmentos (incluye eliminar)'), ('becas_requisito_ver', 'Ver requisitos nativos'), ('becas_requisito_crear', 'Crear requisitos nativos'), ('becas_requisito_editar', 'Editar requisitos nativos (incluye eliminar)'), ('becas_pregunta_ver', 'Ver preguntas globales (cuestionario social)'), ('becas_pregunta_crear', 'Crear preguntas globales'), ('becas_pregunta_editar', 'Editar preguntas globales (incluye activar/desactivar/eliminar)'), ('becas_coordinador_ver', 'Ver coordinadores asignados a segmentos'), ('becas_coordinador_crear', 'Asignar coordinador a un segmento'), ('becas_coordinador_editar', 'Desasignar coordinador de un segmento'), ('becas_convocatoria_ver', 'Ver convocatorias (incluye exportar CSV)'), ('becas_convocatoria_crear', 'Crear convocatorias'), ('becas_convocatoria_editar', 'Editar convocatorias (incluye activar/desactivar)'), ('becas_relevamiento_ver', 'Ver relevamientos de Becas'), ('becas_relevamiento_crear', 'Crear relevamientos de Becas'), ('becas_relevamiento_editar', 'Editar relevamientos (reasignar territorial, reprogramar)'), ('becas_revision_ver', 'Ver relevamientos en revisión y sus formularios'), ('becas_revision_editar', 'Revisar formularios de Becas (iniciar, aprobar, rechazar, terminar)'), ('becas_cupo_ver', 'Ver ocupación y capacidad de cupo por segmento'), ('becas_beneficiario_ver', 'Ver beneficiarios, lista de espera y pendientes'), ('becas_beneficiario_editar', 'Dar de baja, promover y agregar a lista de espera beneficiarios'), ('becas_campo', 'Operar la app de campo de Becas (territorial)'), ('conversacion_operar', 'Operar conversaciones'), ('conversacion_configurar', 'Configurar conversaciones'), ('conversacion_metricas', 'Ver métricas de conversaciones'), ('dashboard_ver', 'Ver dashboard'), ('reporte_ver', 'Ver reportes'), ('config_ver', 'Ver configuración'), ('config_administrar', 'Administrar configuración'), ('institucion_ver', 'Ver instituciones'), ('institucion_administrar', 'Administrar instituciones'), ('usuario_administrar', 'Administrar usuarios'), ('rol_administrar', 'Administrar roles')], 'verbose_name': 'Capacidad', 'verbose_name_plural': 'Capacidades'},
        ),
    ]
