# Generated by Django 4.2.30 on 2026-07-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remapear_permisos_becas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolmeta',
            name='categoria',
            field=models.CharField(choices=[('Backoffice', 'Backoffice'), ('Institución', 'Institución'), ('Portal', 'Portal'), ('Sistema', 'Sistema'), ('ÑACHEC', 'ÑACHEC'), ('Becas', 'Becas'), ('Programa', 'Programa')], default='Backoffice', max_length=20, verbose_name='Categoría'),
        ),
    ]
