# Generated by Django 4.2.20 on 2026-07-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_capacidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolmeta',
            name='categoria',
            field=models.CharField(choices=[('Backoffice', 'Backoffice'), ('Institución', 'Institución'), ('Portal', 'Portal'), ('Sistema', 'Sistema'), ('Becas', 'Becas'), ('Programa', 'Programa')], default='Backoffice', max_length=20, verbose_name='Categoría'),
        ),
    ]
