# Generated by Django 4.2.20 on 2026-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_capacidad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='debe_cambiar_contrasena',
            field=models.BooleanField(default=False, editable=False, verbose_name='Debe cambiar la contraseña'),
        ),
    ]
