# Generated by Django 5.2.17 on 2026-10-08 22:06

from django.db import migrations

# OPS-14 (Ola 7): `ciudadano.eliminar` estaba en el catálogo y en el rol «Gestión de
# Ciudadanos» del seed, y **ninguna vista la evaluaba**: no hay pantalla de borrado de
# ciudadanos. Tildarla no habilitaba nada, que es peor que no ofrecerla —el ABM de Roles
# la mostraba como si diera un permiso real—.
RETIRADAS = [
    ("ciudadano_eliminar", "Eliminar ciudadanos"),
]


def borrar_permisos(apps, schema_editor):
    """Django no borra los `Permission` al sacarlos de `Meta.permissions`.

    Sin esto queda huérfano: no aparece en el ABM de Roles pero sigue tildado en los
    grupos que lo tenían y `rbac.puede()` lo sigue resolviendo. Borrarlo limpia también
    `auth_group_permissions` por cascada. Mismo patrón que `users.0017`.
    """
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="users",
        content_type__model="capacidad",
        codename__in=[codename for codename, _ in RETIRADAS],
    ).delete()


def recrear_permisos(apps, schema_editor):
    """Reversa: recrea el permiso vacío.

    **No** vuelve a tildarlo en ningún rol: la fila de `auth_group_permissions` se fue
    por cascada y la migración no guarda a quién estaba asignada. Revertir deja la
    capacidad en el catálogo y sin asignar, que es lo mismo que daba antes en la
    práctica (ninguna vista la evaluaba).
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    content_type, _ = ContentType.objects.get_or_create(app_label="users", model="capacidad")
    for codename, nombre in RETIRADAS:
        Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": nombre},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_backfill_rolmeta_clave_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capacidad",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("ciudadano_ver", "Ver ciudadanos y legajos"),
                    ("ciudadano_crear", "Crear ciudadanos"),
                    ("ciudadano_editar", "Editar ciudadanos"),
                    ("ciudadano_sensible", "Ver datos sensibles"),
                    ("ciudadano_exportar", "Exportar el padrón de ciudadanos"),
                    ("programa_configurar", "Configurar programas"),
                    ("programa_usuario_administrar", "Administrar los usuarios de su programa"),
                    ("programa_rol_administrar", "Administrar los roles de su programa"),
                    ("dispositivo_ver", "Ver dispositivos"),
                    ("dispositivo_crear", "Crear dispositivos"),
                    ("dispositivo_editar", "Editar dispositivos"),
                    ("dispositivo_validar", "Validar dispositivos"),
                    ("dispositivo_admitir", "Admitir personas en dispositivos"),
                    ("dispositivo_egresar", "Registrar egresos de dispositivos"),
                    ("merendero_ver", "Ver merenderos"),
                    ("merendero_crear", "Crear merenderos"),
                    ("merendero_editar", "Editar merenderos"),
                    ("merendero_validar", "Validar merenderos"),
                    ("merendero_entregar", "Registrar entregas a merenderos"),
                    ("relevamiento_ver", "Ver relevamientos"),
                    ("relevamiento_gestionar", "Gestionar relevamientos"),
                    (
                        "becas_programa_administrar",
                        "Administrar el programa Becas (acceso total, asigna coordinadores)",
                    ),
                    ("becas_usuario_territorial", "Crear y administrar territoriales de los segmentos coordinados"),
                    ("becas_referente", "Operar como Referente dentro del alcance de su Coordinador"),
                    (
                        "becas_coordinador_regional",
                        "Operar como Coordinador Regional dentro de su subsegmento asignado",
                    ),
                    (
                        "becas_programa_proceso_masivo",
                        "Ejecutar el proceso masivo a SIIS (aprueba e informa altas en lote)",
                    ),
                    ("becas_segmento_ver", "Ver segmentos"),
                    ("becas_segmento_crear", "Crear segmentos"),
                    ("becas_segmento_editar", "Editar segmentos (incluye activar/desactivar)"),
                    ("becas_subsegmento_ver", "Ver subsegmentos"),
                    ("becas_subsegmento_crear", "Crear subsegmentos"),
                    ("becas_subsegmento_editar", "Editar subsegmentos (incluye eliminar)"),
                    ("becas_requisito_ver", "Ver requisitos nativos"),
                    ("becas_requisito_crear", "Crear requisitos nativos"),
                    ("becas_requisito_editar", "Editar requisitos nativos (incluye eliminar)"),
                    ("becas_pregunta_ver", "Ver preguntas globales (requisitos generales)"),
                    ("becas_pregunta_crear", "Crear preguntas globales"),
                    ("becas_pregunta_editar", "Editar preguntas globales (incluye activar/desactivar/eliminar)"),
                    ("becas_coordinador_ver", "Ver coordinadores asignados a segmentos"),
                    ("becas_coordinador_crear", "Asignar coordinador a un segmento"),
                    ("becas_coordinador_editar", "Desasignar coordinador de un segmento"),
                    ("becas_convocatoria_ver", "Ver convocatorias (incluye exportar CSV)"),
                    ("becas_convocatoria_crear", "Crear convocatorias"),
                    ("becas_convocatoria_editar", "Editar convocatorias (incluye activar/desactivar)"),
                    ("becas_relevamiento_ver", "Ver relevamientos de Becas"),
                    ("becas_relevamiento_crear", "Crear relevamientos de Becas"),
                    ("becas_relevamiento_editar", "Editar relevamientos (reasignar territorial, reprogramar)"),
                    (
                        "becas_relevamiento_publico",
                        "Crear y ver relevamientos de formulario público (link de inscripción)",
                    ),
                    ("becas_revision_ver", "Ver relevamientos en revisión y sus formularios"),
                    ("becas_revision_editar", "Revisar formularios de Becas (iniciar, aprobar, rechazar, terminar)"),
                    ("becas_cupo_ver", "Ver ocupación y capacidad de cupo por segmento"),
                    ("becas_beneficiario_ver", "Ver beneficiarios, lista de espera y pendientes"),
                    ("becas_beneficiario_editar", "Dar de baja, promover y agregar a lista de espera beneficiarios"),
                    ("becas_reportes_ver", "Ver reportes de Becas"),
                    ("becas_reportes_exportar", "Exportar reportes de Becas"),
                    ("becas_campo", "Operar la app de campo de Becas (territorial)"),
                    ("conversacion_operar", "Operar conversaciones"),
                    ("conversacion_configurar", "Configurar conversaciones"),
                    ("conversacion_metricas", "Ver métricas de conversaciones"),
                    ("dashboard_ver", "Ver dashboard"),
                    ("reporte_ver", "Ver reportes"),
                    ("config_ver", "Ver configuración"),
                    ("config_administrar", "Administrar configuración"),
                    ("institucion_ver", "Ver instituciones"),
                    ("institucion_administrar", "Administrar instituciones"),
                    ("usuario_administrar", "Administrar usuarios"),
                    ("rol_administrar", "Administrar roles"),
                ],
                "verbose_name": "Capacidad",
                "verbose_name_plural": "Capacidades",
            },
        ),
        # REVERSA-NOOP: la reversa recrea el permiso pero no lo vuelve a tildar en
        # ningún rol; esa asignación se perdió con el borrado en cascada.
        migrations.RunPython(borrar_permisos, recrear_permisos),
    ]
