# Generated by Django 4.2.20 on 2026-06-16 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legajos', '0002_remove_derivacionprograma_ciudadano_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('naturaleza', models.CharField(blank=True, choices=[('UN_SOLO_ACTO', 'Un solo acto'), ('PERSISTENTE', 'Persistente')], max_length=20, null=True, verbose_name='Naturaleza')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('INACTIVO', 'Inactivo')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('tiene_turnos', models.BooleanField(default=False, verbose_name='Tiene turnos')),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cupo máximo')),
                ('tiene_lista_espera', models.BooleanField(default=False, verbose_name='Tiene lista de espera')),
                ('icono', models.CharField(default='folder', help_text='Nombre del ícono (ej: people, assessment, school)', max_length=50, verbose_name='Ícono')),
                ('color', models.CharField(default='#6366f1', help_text='Color hex para la UI (ej: #6366f1)', max_length=20, verbose_name='Color')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización en solapas (menor = primero)', verbose_name='Orden')),
                ('subsecretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subsecretaria', verbose_name='Subsecretaría')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('EN_SEGUIMIENTO', 'En Seguimiento'), ('SUSPENDIDO', 'Suspendido'), ('CERRADO', 'Cerrado'), ('DADO_DE_BAJA', 'Dado de Baja')], db_index=True, default='PENDIENTE', max_length=20)),
                ('via_ingreso', models.CharField(choices=[('DIRECTO', 'Ingreso Directo'), ('DERIVACION_INTERNA', 'Derivación Interna'), ('DERIVACION_EXTERNA', 'Derivación Externa'), ('ESPONTANEO', 'Espontáneo')], default='DIRECTO', max_length=30)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, db_index=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, db_index=True, null=True)),
                ('legajo_id', models.UUIDField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_programas', to='legajos.ciudadano')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='programas.programa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a Programa',
                'verbose_name_plural': 'Inscripciones a Programas',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='DerivacionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField()),
                ('urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], db_index=True, default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_programas', to='legajos.ciudadano')),
                ('derivado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_programas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('inscripcion_creada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivacion_origen', to='programas.inscripcionprograma')),
                ('inscripcion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_realizadas', to='programas.inscripcionprograma')),
                ('programa_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_destino', to='programas.programa')),
                ('programa_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_origen', to='programas.programa')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_programas_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Derivación entre Programas',
                'verbose_name_plural': 'Derivaciones entre Programas',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='programa',
            index=models.Index(fields=['estado', 'orden'], name='programas_p_estado_5d03fa_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionprograma',
            index=models.Index(fields=['ciudadano', 'estado'], name='programas_i_ciudada_bb835d_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionprograma',
            index=models.Index(fields=['programa', 'estado'], name='programas_i_program_fbde5c_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionprograma',
            index=models.Index(fields=['estado', 'fecha_inscripcion'], name='programas_i_estado_dc1468_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionprograma',
            unique_together={('ciudadano', 'programa')},
        ),
        migrations.AddIndex(
            model_name='derivacionprograma',
            index=models.Index(fields=['ciudadano', 'estado'], name='programas_d_ciudada_c26441_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacionprograma',
            index=models.Index(fields=['programa_destino', 'estado'], name='programas_d_program_4b87dc_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacionprograma',
            index=models.Index(fields=['estado', 'urgencia'], name='programas_d_estado_ebb5e1_idx'),
        ),
    ]
