# Generated by Django 4.2.20 on 2026-06-23 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0004_remove_derivacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='ENVIADO', max_length=20, verbose_name='Estado')),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('validado_renaper', models.BooleanField(default=False, verbose_name='Validado RENAPER')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('apoderado_nombre', models.CharField(blank=True, max_length=120, verbose_name='Nombre del apoderado')),
                ('apoderado_apellido', models.CharField(blank=True, max_length=120, verbose_name='Apellido del apoderado')),
                ('apoderado_fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento del apoderado')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS latitud')),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS longitud')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Respuestas')),
                ('datos_identificacion', models.JSONField(blank=True, help_text='dni, nombre, apellido, fecha_nacimiento, origen. Se limpia al resolver el ciudadano.', null=True, verbose_name='Datos de identificación (offline)')),
                ('ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formularios_becas', to='legajos.ciudadano', verbose_name='Ciudadano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_becas_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('tipo', models.CharField(choices=[('STRING', 'Texto'), ('INT', 'Número entero'), ('SELECTOR', 'Selector (una opción)'), ('SELECTOR_MULTIPLE', 'Selector múltiple'), ('DATE', 'Fecha'), ('ARCHIVO', 'Archivo adjunto')], max_length=20, verbose_name='Tipo de campo')),
                ('opciones', models.JSONField(blank=True, help_text='Lista de strings; solo para SELECTOR / SELECTOR_MULTIPLE.', null=True, verbose_name='Opciones')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si está inactivo no aparece en el formulario.', verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
            ],
            options={
                'verbose_name': 'Pregunta global',
                'verbose_name_plural': 'Preguntas globales',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cupo_maximo', models.PositiveIntegerField(verbose_name='Cupo máximo')),
                ('requiere_gps', models.BooleanField(default=False, help_text='Si está activo, el formulario del territorial pide lat/lng.', verbose_name='Requiere geolocalización GPS')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TracaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('campo', models.CharField(max_length=200, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, verbose_name='Valor nuevo')),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_formulario', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazas', to='programas.formulario', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Traza de formulario',
                'verbose_name_plural': 'Trazas de formularios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subsegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cupo_maximo', models.PositiveIntegerField(verbose_name='Cupo máximo')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsegmentos', to='programas.segmento', verbose_name='Segmento')),
            ],
            options={
                'verbose_name': 'Subsegmento',
                'verbose_name_plural': 'Subsegmentos',
                'ordering': ['segmento', 'nombre'],
                'unique_together': {('segmento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RequisitoNativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('tipo', models.CharField(choices=[('STRING', 'Texto'), ('INT', 'Número entero'), ('SELECTOR', 'Selector (una opción)'), ('SELECTOR_MULTIPLE', 'Selector múltiple'), ('DATE', 'Fecha'), ('ARCHIVO', 'Archivo adjunto')], max_length=20, verbose_name='Tipo de campo')),
                ('opciones', models.JSONField(blank=True, help_text='Lista de strings; solo para SELECTOR / SELECTOR_MULTIPLE.', null=True, verbose_name='Opciones')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='programas.segmento', verbose_name='Segmento')),
                ('subsegmento', models.ForeignKey(blank=True, help_text='Si es nulo, el requisito es del segmento; si no, del subsegmento.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='programas.subsegmento', verbose_name='Subsegmento')),
            ],
            options={
                'verbose_name': 'Requisito nativo',
                'verbose_name_plural': 'Requisitos nativos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Relevamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(editable=False, max_length=100, verbose_name='Nombre')),
                ('fecha_asignada', models.DateField(verbose_name='Fecha asignada')),
                ('zona', models.CharField(max_length=200, verbose_name='Zona')),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('EN_CURSO', 'En curso'), ('FINALIZANDO', 'Finalizando (sync)'), ('FINALIZADO', 'Finalizado'), ('EN_REVISION', 'En revisión'), ('TERMINADO', 'Terminado')], db_index=True, default='ASIGNADO', max_length=20, verbose_name='Estado')),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relevamientos', to='programas.convocatoria', verbose_name='Convocatoria')),
                ('territorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relevamientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Territorial')),
            ],
            options={
                'verbose_name': 'Relevamiento',
                'verbose_name_plural': 'Relevamientos',
                'ordering': ['-fecha_asignada', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('posicion', models.PositiveIntegerField(verbose_name='Posición')),
                ('promovido', models.BooleanField(default=False, verbose_name='Promovido')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='programas.formulario', verbose_name='Formulario')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='programas.segmento', verbose_name='Segmento')),
            ],
            options={
                'verbose_name': 'Lista de espera',
                'verbose_name_plural': 'Listas de espera',
                'ordering': ['segmento', 'posicion'],
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='relevamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='programas.relevamiento', verbose_name='Relevamiento'),
        ),
        migrations.CreateModel(
            name='CupoSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cupo_ocupado', models.PositiveIntegerField(default=0, verbose_name='Cupo ocupado')),
                ('segmento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cupo', to='programas.segmento', verbose_name='Segmento')),
            ],
            options={
                'verbose_name': 'Cupo de Segmento',
                'verbose_name_plural': 'Cupos de Segmentos',
            },
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocatorias', to='programas.segmento', verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='subsegmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convocatorias', to='programas.subsegmento', verbose_name='Subsegmento'),
        ),
        migrations.CreateModel(
            name='AsignacionCoordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos_coordinados', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_coordinador', to='programas.segmento', verbose_name='Segmento')),
            ],
            options={
                'verbose_name': 'Asignación de coordinador',
                'verbose_name_plural': 'Asignaciones de coordinadores',
                'ordering': ['segmento', 'coordinador'],
            },
        ),
        migrations.AddIndex(
            model_name='relevamiento',
            index=models.Index(fields=['estado', 'fecha_asignada'], name='programas_r_estado_9d845b_idx'),
        ),
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['relevamiento', 'estado'], name='programas_f_relevam_4c6a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['estado'], name='programas_f_estado_e0feb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuposegmento',
            constraint=models.CheckConstraint(check=models.Q(('cupo_ocupado__gte', 0)), name='cupo_segmento_ocupado_no_negativo'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncoordinador',
            unique_together={('segmento', 'coordinador')},
        ),
    ]
