# Generated by Django 4.2.20 on 2026-06-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_convocatoria_formulario_preguntaglobal_segmento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevamiento',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
