# Generated by Django 4.2.20 on 2026-06-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_relevamiento_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsegmento',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
