# Generated by Django 4.2.30 on 2026-07-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0005_formulario_estado_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='becas/adjuntos/%Y/%m/', verbose_name='Archivo')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='programas.formulario', verbose_name='Formulario')),
                ('pregunta_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_formulario', to='programas.preguntaglobal', verbose_name='Pregunta global')),
                ('requisito_nativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_formulario', to='programas.requisitonativo', verbose_name='Requisito nativo')),
            ],
            options={
                'verbose_name': 'Adjunto de formulario',
                'verbose_name_plural': 'Adjuntos de formulario',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='adjuntoformulario',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('pregunta_global__isnull', False), ('requisito_nativo__isnull', True)), models.Q(('pregunta_global__isnull', True), ('requisito_nativo__isnull', False)), _connector='OR'), name='adjunto_formulario_una_sola_referencia'),
        ),
    ]
