# Generated by Django 4.2.20 on 2026-07-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0006_adjuntoformulario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_territorial', to='programas.segmento', verbose_name='Segmento')),
                ('territorial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_territorial', to=settings.AUTH_USER_MODEL, verbose_name='Territorial')),
            ],
            options={
                'verbose_name': 'Asignación de territorial',
                'verbose_name_plural': 'Asignaciones de territoriales',
                'ordering': ['segmento', 'territorial'],
            },
        ),
    ]
