# Generated by Django 4.2.20 on 2026-07-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0007_asignacionterritorial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listaespera',
            index=models.Index(fields=['segmento', 'promovido'], name='programas_l_segment_681d2c_idx'),
        ),
    ]
