# Generated by Django 4.2.20 on 2026-07-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0008_listaespera_programas_l_segment_681d2c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='cerrada_automaticamente',
            field=models.BooleanField(default=False, help_text='La cerró el proceso de vencimientos al pasar la fecha de fin (no una baja manual).', verbose_name='Cerrada por vencimiento'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='cerrada_el',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre automático'),
        ),
    ]
