# Generated by Django 4.2.30 on 2026-07-22 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legajos", "0005_delete_nachec_models"),
        ("programas", "0009_convocatoria_cerrada_automaticamente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDispositivo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(db_index=True, max_length=50, unique=True, verbose_name="Código")),
                ("nombre", models.CharField(max_length=200, unique=True, verbose_name="Nombre")),
                ("descripcion", models.TextField(blank=True, verbose_name="Descripción")),
                ("maneja_camas", models.BooleanField(default=False, verbose_name="Maneja camas")),
                ("activo", models.BooleanField(db_index=True, default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de dispositivo",
                "verbose_name_plural": "Tipos de dispositivo",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Código institucional"),
                ),
                ("nombre", models.CharField(db_index=True, max_length=200, verbose_name="Nombre")),
                ("domicilio", models.CharField(blank=True, max_length=240, verbose_name="Domicilio")),
                ("latitud", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitud", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("responsable_nombre", models.CharField(blank=True, max_length=200, verbose_name="Responsable")),
                (
                    "responsable_documento",
                    models.CharField(blank=True, max_length=20, verbose_name="DNI/CUIT del responsable"),
                ),
                ("contacto_telefono", models.CharField(blank=True, max_length=40, verbose_name="Teléfono")),
                ("contacto_email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("horarios", models.TextField(blank=True, verbose_name="Días y horarios")),
                ("camas_totales", models.PositiveIntegerField(default=0, verbose_name="Camas/plazas totales")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PENDIENTE_VALIDACION", "Pendiente de validación"),
                            ("ACTIVO", "Activo"),
                            ("OBSERVADO", "Observado"),
                            ("RECHAZADO", "Rechazado"),
                            ("INACTIVO", "Inactivo"),
                            ("CERRADO", "Cerrado"),
                        ],
                        db_index=True,
                        default="BORRADOR",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispositivos",
                        to="programas.tipodispositivo",
                        verbose_name="Tipo de dispositivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo",
                "verbose_name_plural": "Dispositivos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cama",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50, verbose_name="Código")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("RESERVADA", "Reservada"),
                            ("OCUPADA", "Ocupada"),
                            ("FUERA_SERVICIO", "Fuera de servicio"),
                        ],
                        db_index=True,
                        default="DISPONIBLE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="camas",
                        to="programas.dispositivo",
                        verbose_name="Dispositivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cama/plaza",
                "verbose_name_plural": "Camas/plazas",
                "ordering": ["dispositivo", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Admision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("fecha_ingreso", models.DateTimeField(verbose_name="Fecha de ingreso")),
                ("fecha_egreso", models.DateTimeField(blank=True, null=True, verbose_name="Fecha de egreso")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOLICITADO", "Solicitado"),
                            ("EN_REVISION", "En revisión"),
                            ("LISTA_ESPERA", "Lista de espera"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("ALOJADO", "Alojado"),
                            ("EGRESADO", "Egresado"),
                            ("TRASLADADO", "Trasladado"),
                        ],
                        db_index=True,
                        default="SOLICITADO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("es_reingreso", models.BooleanField(default=False, verbose_name="Es reingreso")),
                ("motivo_egreso", models.TextField(blank=True, verbose_name="Motivo de egreso")),
                (
                    "destino_egreso",
                    models.CharField(blank=True, max_length=240, verbose_name="Destino de egreso/traslado"),
                ),
                (
                    "cama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admisiones",
                        to="programas.cama",
                        verbose_name="Cama/plaza",
                    ),
                ),
                (
                    "ciudadano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admisiones_dispositivos",
                        to="legajos.ciudadano",
                        verbose_name="Ciudadano",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admisiones",
                        to="programas.dispositivo",
                        verbose_name="Dispositivo",
                    ),
                ),
                (
                    "inscripcion_programa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admisiones_dispositivos",
                        to="programas.inscripcionprograma",
                        verbose_name="Membresía al programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admisión/estadía",
                "verbose_name_plural": "Admisiones/estadías",
                "ordering": ["-fecha_ingreso"],
            },
        ),
        migrations.AddIndex(
            model_name="dispositivo",
            index=models.Index(fields=["tipo", "estado"], name="programas_d_tipo_id_62ea27_idx"),
        ),
        migrations.AddIndex(
            model_name="dispositivo",
            index=models.Index(fields=["nombre", "estado"], name="programas_d_nombre_f7e479_idx"),
        ),
        migrations.AddIndex(
            model_name="cama",
            index=models.Index(fields=["dispositivo", "estado"], name="programas_c_disposi_74c50d_idx"),
        ),
        migrations.AddConstraint(
            model_name="cama",
            constraint=models.UniqueConstraint(
                fields=("dispositivo", "codigo"), name="cama_codigo_unico_por_dispositivo"
            ),
        ),
        migrations.AddIndex(
            model_name="admision",
            index=models.Index(fields=["ciudadano", "estado"], name="programas_a_ciudada_145b5e_idx"),
        ),
        migrations.AddIndex(
            model_name="admision",
            index=models.Index(fields=["dispositivo", "estado"], name="programas_a_disposi_772417_idx"),
        ),
        migrations.AddIndex(
            model_name="admision",
            index=models.Index(fields=["cama", "estado"], name="programas_a_cama_id_6c2209_idx"),
        ),
    ]
