# Generated by Django 4.2.30 on 2026-07-22 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programas", "0010_dispositivos_modelos_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntregaMercaderia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField(db_index=True, verbose_name="Fecha de entrega")),
                ("cantidad_kits", models.PositiveIntegerField(verbose_name="Cantidad de kits")),
                ("servicio", models.CharField(blank=True, max_length=120, verbose_name="Servicio")),
                (
                    "responsable_receptor",
                    models.CharField(blank=True, max_length=200, verbose_name="Responsable receptor"),
                ),
                ("observaciones", models.TextField(blank=True, verbose_name="Observaciones")),
                ("anulada", models.BooleanField(db_index=True, default=False, verbose_name="Anulada")),
            ],
            options={
                "verbose_name": "Entrega de mercadería",
                "verbose_name_plural": "Entregas de mercadería",
                "ordering": ["-fecha", "-creado"],
            },
        ),
        migrations.CreateModel(
            name="Merendero",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Código institucional"),
                ),
                ("nombre", models.CharField(db_index=True, max_length=200, verbose_name="Nombre")),
                ("domicilio", models.CharField(max_length=240, verbose_name="Domicilio")),
                ("zona", models.CharField(blank=True, max_length=120, verbose_name="Zona")),
                ("barrio", models.CharField(blank=True, max_length=120, verbose_name="Barrio")),
                ("telefono", models.CharField(blank=True, max_length=40, verbose_name="Teléfono")),
                ("responsable_nombre", models.CharField(max_length=200, verbose_name="Responsable")),
                (
                    "responsable_documento",
                    models.CharField(blank=True, max_length=20, verbose_name="DNI/CUIT del responsable"),
                ),
                (
                    "responsable_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email del responsable"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("SUSPENDIDO", "Suspendido"), ("CERRADO", "Cerrado")],
                        db_index=True,
                        default="ACTIVO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merendero",
                "verbose_name_plural": "Merenderos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudMerendero",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "documentacion",
                    models.FileField(
                        upload_to="merenderos/solicitudes/%Y/%m/", verbose_name="Documentación respaldatoria"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En revisión"),
                            ("OBSERVADA", "Observada"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        db_index=True,
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("observaciones", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "merendero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="programas.merendero",
                        verbose_name="Merendero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de merendero",
                "verbose_name_plural": "Solicitudes de merenderos",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="PrestacionMensual",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("anio", models.PositiveSmallIntegerField(verbose_name="Año")),
                ("mes", models.PositiveSmallIntegerField(verbose_name="Mes")),
                ("servicios", models.JSONField(blank=True, default=list, verbose_name="Servicios habilitados")),
                ("observaciones", models.TextField(blank=True, verbose_name="Observaciones")),
                ("anulada", models.BooleanField(db_index=True, default=False, verbose_name="Anulada")),
                (
                    "merendero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestaciones_mensuales",
                        to="programas.merendero",
                        verbose_name="Merendero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestación alimentaria mensual",
                "verbose_name_plural": "Prestaciones alimentarias mensuales",
                "ordering": ["-anio", "-mes"],
            },
        ),
        migrations.CreateModel(
            name="PrestacionDiaria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("dia", models.PositiveSmallIntegerField(verbose_name="Día")),
                (
                    "servicio",
                    models.CharField(
                        choices=[
                            ("DESAYUNO", "Desayuno/colación"),
                            ("ALMUERZO", "Almuerzo"),
                            ("MERIENDA", "Merienda/colación"),
                            ("CENA", "Cena"),
                        ],
                        max_length=20,
                        verbose_name="Servicio",
                    ),
                ),
                ("raciones", models.PositiveIntegerField(verbose_name="Raciones")),
                ("observaciones", models.TextField(blank=True, verbose_name="Observaciones")),
                ("anulada", models.BooleanField(db_index=True, default=False, verbose_name="Anulada")),
                (
                    "firmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestaciones_diarias_firmadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Firmado por",
                    ),
                ),
                (
                    "prestacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas_diarias",
                        to="programas.prestacionmensual",
                        verbose_name="Prestación mensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea diaria de prestación alimentaria",
                "verbose_name_plural": "Líneas diarias de prestación alimentaria",
                "ordering": ["prestacion", "dia", "servicio"],
            },
        ),
        migrations.AddIndex(
            model_name="merendero",
            index=models.Index(fields=["nombre", "estado"], name="programas_m_nombre_5ee4e9_idx"),
        ),
        migrations.AddField(
            model_name="entregamercaderia",
            name="merendero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entregas_mercaderia",
                to="programas.merendero",
                verbose_name="Merendero",
            ),
        ),
        migrations.AddIndex(
            model_name="solicitudmerendero",
            index=models.Index(fields=["merendero", "estado"], name="programas_s_merende_b139b7_idx"),
        ),
        migrations.AddConstraint(
            model_name="prestacionmensual",
            constraint=models.UniqueConstraint(
                fields=("merendero", "anio", "mes"), name="prestacion_mensual_unica_por_merendero"
            ),
        ),
        migrations.AddConstraint(
            model_name="prestacionmensual",
            constraint=models.CheckConstraint(
                check=models.Q(("mes__gte", 1), ("mes__lte", 12)), name="prestacion_mensual_mes_valido"
            ),
        ),
        migrations.AddConstraint(
            model_name="prestaciondiaria",
            constraint=models.UniqueConstraint(
                fields=("prestacion", "dia", "servicio"), name="prestacion_diaria_unica_por_servicio"
            ),
        ),
        migrations.AddConstraint(
            model_name="prestaciondiaria",
            constraint=models.CheckConstraint(
                check=models.Q(("dia__gte", 1), ("dia__lte", 31)), name="prestacion_diaria_dia_valido"
            ),
        ),
        migrations.AddIndex(
            model_name="entregamercaderia",
            index=models.Index(fields=["merendero", "fecha"], name="programas_e_merende_9f9697_idx"),
        ),
    ]
