# Generated by Django 4.2.30 on 2026-07-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0012_crear_programas_dispositivos_merenderos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoTipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('seccion', models.CharField(max_length=200, verbose_name='Sección')),
                ('nombre', models.CharField(max_length=240, verbose_name='Nombre')),
                ('tipo_campo', models.CharField(choices=[('STRING', 'Texto'), ('INT', 'Número entero'), ('SELECTOR', 'Selector (una opción)'), ('SELECTOR_MULTIPLE', 'Selector múltiple'), ('DATE', 'Fecha'), ('ARCHIVO', 'Archivo adjunto')], max_length=20, verbose_name='Tipo de campo')),
                ('opciones', models.JSONField(blank=True, help_text='Lista de strings; solo para SELECTOR / SELECTOR_MULTIPLE.', null=True, verbose_name='Opciones')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_configurados', to='programas.tipodispositivo', verbose_name='Tipo de dispositivo')),
            ],
            options={
                'verbose_name': 'Campo de tipo de dispositivo',
                'verbose_name_plural': 'Campos de tipos de dispositivo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='campotipodispositivo',
            constraint=models.UniqueConstraint(fields=('tipo_dispositivo', 'seccion', 'nombre'), name='uniq_campo_tipo_dispositivo_seccion_nombre'),
        ),
    ]
