# Generated by Django 4.2.30 on 2026-07-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('programas', '0013_campotipodispositivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_roles', to='programas.dispositivo', verbose_name='Dispositivo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_dispositivos', to='auth.group', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Asignación a dispositivo',
                'verbose_name_plural': 'Asignaciones a dispositivos',
                'ordering': ['dispositivo', 'rol'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignaciondispositivo',
            constraint=models.UniqueConstraint(fields=('dispositivo', 'rol'), name='asignacion_dispositivo_unica_por_rol'),
        ),
    ]
