# Generated by Django 4.2.30 on 2026-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0014_dispositivos_alcance_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='localidad',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Localidad'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['nombre', 'localidad'], name='programas_d_nombre_1aa831_idx'),
        ),
    ]
