# Generated by Django 4.2.30 on 2026-07-24 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0015_legajo_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrazaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('accion', models.CharField(max_length=40, verbose_name='Acción')),
                ('estado_anterior', models.CharField(blank=True, max_length=30, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=30, verbose_name='Estado nuevo')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazas', to='programas.dispositivo', verbose_name='Dispositivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_dispositivos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Traza de dispositivo',
                'verbose_name_plural': 'Trazas de dispositivos',
                'ordering': ['creado_en', 'id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
    ]
