# Generated by Django 4.2.30 on 2026-07-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programas", "0016_trazabilidad_dispositivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trazadispositivo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trazas_dispositivos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
