# Generated by Django 4.2.30 on 2026-07-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programas", "0017_proteger_usuario_traza_dispositivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trazadispositivo",
            name="dispositivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trazas",
                to="programas.dispositivo",
                verbose_name="Dispositivo",
            ),
        ),
    ]
