# Generated by Django 4.2.30 on 2026-07-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programas", "0018_proteger_traza_dispositivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipodispositivo",
            name="umbral_ocupacion_amarillo",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="Ocupación desde la que el semáforo es amarillo (%)",
            ),
        ),
        migrations.AddField(
            model_name="tipodispositivo",
            name="umbral_ocupacion_rojo",
            field=models.PositiveSmallIntegerField(
                default=80,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="Ocupación desde la que el semáforo es rojo (%)",
            ),
        ),
    ]
