# Generated by Django 4.2.30 on 2026-07-24

from django.db import migrations, models
from django.db.models import Count


def validar_admisiones_alojadas_duplicadas(apps, schema_editor):
    Admision = apps.get_model("programas", "Admision")
    hay_duplicadas = (
        Admision.objects.filter(cama__isnull=False, estado="ALOJADO")
        .values("cama_id")
        .annotate(cantidad=Count("id"))
        .filter(cantidad__gt=1)
        .exists()
    )
    if hay_duplicadas:
        raise RuntimeError(
            "No se puede aplicar la restricción de camas: hay camas con más de una estadía alojada. "
            "Reasigná o egresá las estadías duplicadas antes de reintentar la migración."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("programas", "0019_tipodispositivo_umbral_ocupacion_amarillo_and_more"),
    ]

    operations = [
        migrations.RunPython(validar_admisiones_alojadas_duplicadas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="admision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cama__isnull", False), ("estado", "ALOJADO")),
                fields=("cama",),
                name="admision_una_cama_alojada",
            ),
        ),
    ]
