# Generated by Django 4.2.30 on 2026-07-27 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0020_admision_admision_una_cama_alojada'),
    ]

    operations = [
        migrations.AddField(
            model_name='merendero',
            name='dias_horarios',
            field=models.CharField(blank=True, max_length=240, verbose_name='Días y horarios'),
        ),
        migrations.AddField(
            model_name='merendero',
            name='estado_actualizado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización de estado'),
        ),
        migrations.AddField(
            model_name='merendero',
            name='estado_actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merenderos_estado_actualizado', to=settings.AUTH_USER_MODEL, verbose_name='Estado actualizado por'),
        ),
        migrations.AddField(
            model_name='prestacionmensual',
            name='observaciones_por_dia',
            field=models.JSONField(blank=True, default=dict, verbose_name='Observaciones por día'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='barrio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código institucional'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='dias_horarios',
            field=models.CharField(blank=True, max_length=240, verbose_name='Días y horarios'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='domicilio',
            field=models.CharField(blank=True, max_length=240, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='responsable_documento',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI/CUIT del responsable'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='responsable_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del responsable'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='responsable_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='telefono',
            field=models.CharField(blank=True, max_length=40, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='validada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='validada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_merendero_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validada por'),
        ),
        migrations.AddField(
            model_name='solicitudmerendero',
            name='zona',
            field=models.CharField(blank=True, max_length=120, verbose_name='Zona'),
        ),
    ]
