# Generated by Django 4.2.30 on 2026-07-28 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0021_operativa_merenderos'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision',
            name='responsable_egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos_dispositivos', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del egreso'),
        ),
        migrations.AddField(
            model_name='admision',
            name='respuestas_f00',
            field=models.JSONField(blank=True, default=dict, verbose_name='Respuestas F-00'),
        ),
        migrations.CreateModel(
            name='EsperaAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('posicion', models.PositiveIntegerField()),
                ('promovida', models.BooleanField(db_index=True, default=False)),
                ('admision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='espera', to='programas.admision')),
            ],
            options={
                'verbose_name': 'Espera de admisión',
                'verbose_name_plural': 'Esperas de admisión',
                'ordering': ['posicion', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='esperaadmision',
            constraint=models.UniqueConstraint(condition=models.Q(('promovida', False)), fields=('admision',), name='espera_admision_activa_unica'),
        ),
    ]
