# Generated by Django 4.2.30 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0022_admisiones_operativa"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="origen_traslado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="traslados_destino",
                to="programas.admision",
                verbose_name="Admisión de origen del traslado",
            ),
        ),
        migrations.CreateModel(
            name="ArchivoAdmision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("archivo", models.FileField(upload_to="admisiones/f00/")),
                (
                    "admision",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="archivos_f00", to="programas.admision"),
                ),
                (
                    "campo",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="archivos_admisiones", to="programas.campotipodispositivo"),
                ),
            ],
            options={"verbose_name": "Archivo de admisión", "verbose_name_plural": "Archivos de admisión"},
        ),
        migrations.AddConstraint(
            model_name="archivoadmision",
            constraint=models.UniqueConstraint(fields=("admision", "campo"), name="archivo_f00_unico_por_campo"),
        ),
    ]
