# Generated by Django 4.2.30 on 2026-07-28

from django.db import migrations, models


def asignar_roles_existentes(apps, schema_editor):
    Campo = apps.get_model("programas", "CampoTipoDispositivo")
    Campo.objects.filter(nombre__in=["Ingreso mensual", "Ingreso total mensual"]).update(rol_calculo="INGRESO")
    Campo.objects.filter(
        nombre__in=["Alquiler", "Créditos", "Cuotas", "Medicamentos", "Transporte", "Transporte y otros", "Otros egresos"]
    ).update(rol_calculo="EGRESO")


class Migration(migrations.Migration):
    dependencies = [("programas", "0023_admision_traslados_y_archivos")]

    operations = [
        migrations.AddField(
            model_name="campotipodispositivo",
            name="rol_calculo",
            field=models.CharField(
                choices=[("NINGUNO", "No interviene en totales"), ("INGRESO", "Ingreso para saldo estimado"), ("EGRESO", "Egreso para saldo estimado")],
                default="NINGUNO",
                max_length=10,
                verbose_name="Rol en totales F-00",
            ),
        ),
        migrations.RunPython(asignar_roles_existentes, migrations.RunPython.noop),
    ]
