# Generated by Django 4.2.30 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("programas", "0024_campotipodispositivo_rol_calculo")]

    operations = [
        migrations.AddConstraint(
            model_name="admision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ALOJADO")),
                fields=("ciudadano", "dispositivo"),
                name="admision_una_estadia_activa_por_dispositivo",
            ),
        ),
    ]
