# Generated by Django 4.2.30 on 2026-07-29 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programas", "0025_admision_una_estadia_activa"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroDiario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField(db_index=True, verbose_name="Fecha")),
                (
                    "turno",
                    models.CharField(
                        choices=[("MANIANA", "Mañana"), ("TARDE", "Tarde"), ("NOCHE", "Noche")],
                        max_length=10,
                        verbose_name="Turno",
                    ),
                ),
                ("camas_totales", models.PositiveIntegerField(default=0, editable=False)),
                ("ingresos", models.PositiveIntegerField(default=0, editable=False)),
                ("egresos", models.PositiveIntegerField(default=0, editable=False)),
                ("ocupacion_nocturna", models.PositiveIntegerField(default=0, editable=False)),
                ("camas_disponibles", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "observaciones",
                    models.JSONField(blank=True, default=dict, verbose_name="Observaciones por concepto"),
                ),
                ("observaciones_generales", models.TextField(blank=True, verbose_name="Observaciones generales")),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_diarios",
                        to="programas.dispositivo",
                        verbose_name="Dispositivo",
                    ),
                ),
                (
                    "firmado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partes_diarios_dispositivos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Firmado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro diario F-01",
                "verbose_name_plural": "Registros diarios F-01",
                "ordering": ["-fecha", "turno"],
            },
        ),
        migrations.AddConstraint(
            model_name="registrodiario",
            constraint=models.UniqueConstraint(
                fields=("dispositivo", "fecha", "turno"), name="registro_diario_unico_por_turno"
            ),
        ),
    ]
