# Generated by Django 4.2.30 on 2026-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0026_registrodiario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_padron',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de referencia del padrón'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fuente_padron',
            field=models.CharField(blank=True, max_length=240, verbose_name='Fuente del padrón'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='responsable_padron',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsable de la carga del padrón'),
        ),
        migrations.AddField(
            model_name='merendero',
            name='fecha_padron',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de referencia del padrón'),
        ),
        migrations.AddField(
            model_name='merendero',
            name='fuente_padron',
            field=models.CharField(blank=True, max_length=240, verbose_name='Fuente del padrón'),
        ),
        migrations.AddField(
            model_name='merendero',
            name='responsable_padron',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsable de la carga del padrón'),
        ),
    ]
