# Generated by Django 4.2.30 on 2026-07-29 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0027_import_padron_procedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodispositivo',
            name='dias_actualizacion_amarillo',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Días máximos de actualización para amarillo'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='dias_actualizacion_verde',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Días máximos de actualización para verde'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='umbral_completitud_amarillo',
            field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Completitud desde la que el semáforo es amarillo (%)'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='umbral_completitud_verde',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Completitud desde la que el semáforo es verde (%)'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='umbral_disponibilidad_verde',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disponibilidad mínima para semáforo verde (%)'),
        ),
    ]
