# Generated by Django 4.2.30 on 2026-08-07 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0036_relevamiento_fecha_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='pausa_motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de la pausa'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='pausado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pausado'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='pausado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pausa'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='pausado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pausado por'),
        ),
        migrations.AddField(
            model_name='relevamiento',
            name='pausa_motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de la pausa'),
        ),
        migrations.AddField(
            model_name='relevamiento',
            name='pausado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pausado'),
        ),
        migrations.AddField(
            model_name='relevamiento',
            name='pausado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pausa'),
        ),
        migrations.AddField(
            model_name='relevamiento',
            name='pausado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pausado por'),
        ),
        migrations.AddField(
            model_name='segmento',
            name='pausa_motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de la pausa'),
        ),
        migrations.AddField(
            model_name='segmento',
            name='pausado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pausado'),
        ),
        migrations.AddField(
            model_name='segmento',
            name='pausado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pausa'),
        ),
        migrations.AddField(
            model_name='segmento',
            name='pausado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pausado por'),
        ),
        migrations.AddField(
            model_name='subsegmento',
            name='pausa_motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de la pausa'),
        ),
        migrations.AddField(
            model_name='subsegmento',
            name='pausado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pausado'),
        ),
        migrations.AddField(
            model_name='subsegmento',
            name='pausado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pausa'),
        ),
        migrations.AddField(
            model_name='subsegmento',
            name='pausado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pausado por'),
        ),
        migrations.CreateModel(
            name='RegistroPausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo_entidad', models.CharField(db_index=True, max_length=30, verbose_name='Tipo de elemento')),
                ('objeto_id', models.PositiveBigIntegerField(db_index=True, verbose_name='ID del elemento')),
                ('objeto_nombre', models.CharField(max_length=255, verbose_name='Elemento')),
                ('accion', models.CharField(choices=[('PAUSAR', 'Pausar'), ('REANUDAR', 'Reanudar')], max_length=10, verbose_name='Acción')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_pausa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de pausa',
                'verbose_name_plural': 'Registros de pausa',
                'ordering': ['-creado', '-pk'],
            },
        ),
    ]
