# Generated by Django 4.2.30 on 2026-08-07 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0037_pausas_operativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionterritorial',
            name='coordinador_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territoriales_regionales', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador regional'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convocatorias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='responsable_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convocatorias_regionales', to=settings.AUTH_USER_MODEL, verbose_name='Responsable regional'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('localidades', models.ManyToManyField(related_name='regiones', to='programas.subsegmento', verbose_name='Localidades')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionReferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referentes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador')),
                ('referente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_referente', to=settings.AUTH_USER_MODEL, verbose_name='Referente')),
            ],
            options={
                'verbose_name': 'Asignación de referente',
                'verbose_name_plural': 'Asignaciones de referentes',
                'ordering': ['coordinador', 'referente'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionCoordinadorRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('coordinador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_coordinador_regional', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador regional')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinadores_asignados', to='programas.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Asignación de coordinador regional',
                'verbose_name_plural': 'Asignaciones de coordinadores regionales',
                'ordering': ['region', 'coordinador'],
            },
        ),
    ]
