# Generated by Django 4.2.30 on 2026-08-07 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0038_asignacionterritorial_coordinador_regional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('convocatorias_transferidas', models.PositiveIntegerField(default=0)),
                ('territoriales_transferidos', models.PositiveIntegerField(default=0)),
                ('coordinador_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_regionales_entrantes', to=settings.AUTH_USER_MODEL, verbose_name='Destino')),
                ('coordinador_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_regionales_salientes', to=settings.AUTH_USER_MODEL, verbose_name='Origen')),
                ('ejecutado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_regionales_ejecutadas', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='programas.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Transferencia regional',
                'verbose_name_plural': 'Transferencias regionales',
                'ordering': ['-creado'],
            },
        ),
    ]
