# Generated by Django 4.2.30 on 2026-08-07 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0039_transferenciaregional'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevamiento',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=100, help_text='Cantidad máxima de personas que pueden cargarse en este relevamiento.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cupo de personas'),
        ),
    ]
