# Generated by Django 4.2.30 on 2026-08-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0040_relevamiento_cupo_maximo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='localidades',
        ),
        migrations.RemoveField(
            model_name='transferenciaregional',
            name='coordinador_destino',
        ),
        migrations.RemoveField(
            model_name='transferenciaregional',
            name='coordinador_origen',
        ),
        migrations.RemoveField(
            model_name='transferenciaregional',
            name='ejecutado_por',
        ),
        migrations.RemoveField(
            model_name='transferenciaregional',
            name='region',
        ),
        migrations.RemoveField(
            model_name='asignacionterritorial',
            name='coordinador_regional',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='creada_por',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='responsable_regional',
        ),
        migrations.DeleteModel(
            name='AsignacionCoordinadorRegional',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='TransferenciaRegional',
        ),
    ]
