# Generated by Django 4.2.20 on 2026-08-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0041_remove_region_localidades_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subsegmento',
            name='uniq_subsegmento_siis_por_segmento',
        ),
        migrations.RemoveField(
            model_name='subsegmento',
            name='siis_segmento_id',
        ),
        migrations.AlterField(
            model_name='validacionsis',
            name='id_segmento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validacionsis',
            name='sexo',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
