# Generated by Django 4.2.20 on 2026-08-11 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0043_siis_programa_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsegmento',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsegmentos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Referente asignado'),
        ),
    ]
