# Generated by Django 4.2.20 on 2026-08-13 11:01
"""Nivel Programa (SIIS) por encima de los segmentos.

Programa → Segmento → Subsegmento. El vínculo con SIIS (id, foto congelada,
estado y fechas) se muda del segmento a la entidad nueva; cada segmento
vinculado genera su programa y queda colgado de él. Los segmentos históricos
sin vínculo quedan con programa nulo (el alta nueva siempre lo exige).

La reversión de los datos no es automática (RunPython.noop): antes de revertir,
respaldar la base — al volver atrás, el vínculo SIIS de los segmentos se pierde.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _crear_programas(apps, schema_editor):
    """Un ProgramaSiis por cada segmento vinculado, desde su foto congelada.

    La unicidad previa (uniq_segmento_siis_programa) garantiza a lo sumo un
    segmento por programa, así que el get_or_create nunca pisa datos de otro.
    """
    Segmento = apps.get_model("programas", "Segmento")
    ProgramaSiis = apps.get_model("programas", "ProgramaSiis")
    for segmento in Segmento.objects.exclude(siis_programa_id__isnull=True).iterator():
        datos = segmento.siis_programa_datos or {}
        programa, _ = ProgramaSiis.objects.get_or_create(
            siis_programa_id=segmento.siis_programa_id,
            defaults={
                "nombre": datos.get("nombre") or segmento.nombre,
                "siis_programa_datos": datos,
                "siis_programa_estado": segmento.siis_programa_estado or "",
                "siis_vinculado_en": segmento.siis_vinculado_en,
                "siis_verificado_en": segmento.siis_verificado_en,
            },
        )
        segmento.programa = programa
        segmento.save(update_fields=["programa"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0044_subsegmento_referente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaSiis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('pausado', models.BooleanField(db_index=True, default=False, verbose_name='Pausado')),
                ('pausa_motivo', models.TextField(blank=True, default='', verbose_name='Motivo de la pausa')),
                ('pausado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pausa')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('siis_programa_id', models.PositiveIntegerField(unique=True, verbose_name='ID de programa SIIS')),
                ('siis_programa_datos', models.JSONField(blank=True, default=dict, verbose_name='Detalle del programa SIIS')),
                ('siis_programa_estado', models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('DESCONOCIDO', 'Desconocido')], db_index=True, default='', max_length=20, verbose_name='Estado actual del programa en SIIS')),
                ('siis_vinculado_en', models.DateTimeField(blank=True, null=True, verbose_name='Programa SIIS vinculado el')),
                ('siis_verificado_en', models.DateTimeField(blank=True, null=True, verbose_name='Última verificación con SIIS')),
            ],
            options={
                'verbose_name': 'Programa SIIS',
                'verbose_name_plural': 'Programas SIIS',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='programasiis',
            name='pausado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pausado por'),
        ),
        migrations.AddField(
            model_name='segmento',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segmentos', to='programas.programasiis', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='requisitonativo',
            name='programa',
            field=models.ForeignKey(blank=True, help_text='Si se indica, el requisito es del programa y lo heredan todos sus segmentos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='programas.programasiis', verbose_name='Programa'),
        ),
        # Los datos se copian con los campos viejos todavía presentes.
        migrations.RunPython(_crear_programas, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='segmento',
            name='uniq_segmento_siis_programa',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='siis_programa_datos',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='siis_programa_estado',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='siis_programa_id',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='siis_verificado_en',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='siis_vinculado_en',
        ),
        migrations.AlterField(
            model_name='requisitonativo',
            name='segmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='programas.segmento', verbose_name='Segmento'),
        ),
        migrations.AddConstraint(
            model_name='segmento',
            constraint=models.UniqueConstraint(fields=('programa', 'nombre'), name='uniq_segmento_programa_nombre'),
        ),
    ]
