# Generated by Django 5.2.17 on 2026-08-19 02:37

from datetime import datetime, time

from django.db import migrations, models
from django.utils import timezone


def conservar_dias_como_franja_completa(apps, schema_editor):
    Relevamiento = apps.get_model("programas", "Relevamiento")
    zona = timezone.get_current_timezone()
    for relevamiento in Relevamiento.objects.all().iterator():
        dia_desde = relevamiento.fecha_asignada.date()
        dia_hasta = relevamiento.fecha_hasta.date()
        relevamiento.fecha_asignada = timezone.make_aware(datetime.combine(dia_desde, time.min), zona)
        relevamiento.fecha_hasta = timezone.make_aware(datetime.combine(dia_hasta, time(23, 59, 59)), zona)
        relevamiento.save(update_fields=["fecha_asignada", "fecha_hasta"])


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0045_programa_siis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevamiento',
            name='fecha_asignada',
            field=models.DateTimeField(verbose_name='Fecha y hora desde'),
        ),
        migrations.AlterField(
            model_name='relevamiento',
            name='fecha_hasta',
            field=models.DateTimeField(verbose_name='Fecha y hora hasta'),
        ),
        migrations.RunPython(conservar_dias_como_franja_completa, migrations.RunPython.noop),
    ]
