# Generated by Django 4.2.30 on 2026-08-14 15:40

from django.db import migrations, models


def completar_fechas_desde_trazas(apps, schema_editor):
    Formulario = apps.get_model("programas", "Formulario")
    TracaFormulario = apps.get_model("programas", "TracaFormulario")

    fechas = {}
    trazas = (
        TracaFormulario.objects.filter(campo__iexact="estado")
        .order_by("created_at", "pk")
        .values_list("formulario_id", "valor_nuevo", "created_at")
    )
    for formulario_id, valor_nuevo, creada_en in trazas.iterator():
        nuevo = (valor_nuevo or "").upper()
        datos = fechas.setdefault(formulario_id, {})
        if "APROBADO" in nuevo:
            datos["fecha_aprobacion"] = creada_en
        if "RECHAZADO" in nuevo:
            datos["fecha_rechazo"] = creada_en

    for formulario_id, datos in fechas.items():
        Formulario.objects.filter(pk=formulario_id).update(**datos)


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0045_programa_siis'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de rechazo'),
        ),
        migrations.RunPython(completar_fechas_desde_trazas, migrations.RunPython.noop),
    ]
