# Generated by Django 4.2.20 on 2026-08-24 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programas", "0048_ampliar_validacionsis_id_consulta"),
    ]

    operations = [
        migrations.AddField(
            model_name="relevamiento",
            name="confirmar_por_email",
            field=models.BooleanField(
                default=False,
                help_text="Al inscribirse por el link, la persona recibe un correo con su comprobante.",
                verbose_name="Enviar confirmación por correo",
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="tipo",
            field=models.CharField(
                choices=[("TERRITORIAL", "Territorial"), ("PUBLICO", "Formulario público")],
                db_index=True,
                default="TERRITORIAL",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="token_publico",
            field=models.UUIDField(
                blank=True, editable=False, null=True, unique=True, verbose_name="Token del link público"
            ),
        ),
        migrations.AlterField(
            model_name="relevamiento",
            name="territorial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relevamientos_asignados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Territorial",
            ),
        ),
        migrations.AlterField(
            model_name="relevamiento",
            name="zona",
            field=models.CharField(blank=True, max_length=200, verbose_name="Zona"),
        ),
        migrations.AddConstraint(
            model_name="relevamiento",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("territorial__isnull", False), ("tipo", "TERRITORIAL")),
                    models.Q(("territorial__isnull", True), ("tipo", "PUBLICO")),
                    _connector="OR",
                ),
                name="relevamiento_tipo_territorial_coherente",
            ),
        ),
    ]
