# Generated by Django 4.2.20 on 2026-08-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0049_relevamiento_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevamiento',
            name='padron_archivo',
            field=models.FileField(blank=True, null=True, upload_to='becas/padrones/', verbose_name='Padrón de habilitados (archivo)'),
        ),
        migrations.CreateModel(
            name='PadronHabilitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('relevamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padron', to='programas.relevamiento', verbose_name='Relevamiento')),
            ],
            options={
                'verbose_name': 'Habilitado del padrón',
                'verbose_name_plural': 'Habilitados del padrón',
                'indexes': [models.Index(fields=['relevamiento', 'dni', 'sexo'], name='programas_p_relevam_8abf0a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='padronhabilitado',
            constraint=models.UniqueConstraint(fields=('relevamiento', 'dni'), name='uniq_padron_dni_relevamiento'),
        ),
    ]
