# Generated by Django 5.2.17 on 2026-08-26 04:18

import programas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0050_padron_habilitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntoformulario',
            name='archivo',
            field=models.FileField(upload_to=programas.models.ruta_adjunto_becas, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='relevamiento',
            name='padron_archivo',
            field=models.FileField(blank=True, null=True, upload_to=programas.models.ruta_padron_becas, verbose_name='Padrón de habilitados (archivo)'),
        ),
    ]
