# Generated by Django 4.2.20 on 2026-08-26 17:59
#
# Cambio 44: solo metadatos. ``confirmar_por_email`` existe desde 0049 y no
# cambia de tipo, default ni nulabilidad; lo que cambia es qué significa —dejó
# de ser «el comprobante del link público» para cubrir también los avisos de
# resolución y el canal territorial—. Va igual para que ``makemigrations
# --check`` quede limpio. Sin efecto sobre los datos.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programas", "0052_renombrar_adjuntos_existentes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relevamiento",
            name="confirmar_por_email",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Avisa por correo cuando se resuelve el formulario: aprobado, en lista de espera o "
                    "rechazado. En los relevamientos con link público, además manda el comprobante al "
                    "inscribirse."
                ),
                verbose_name="Avisar por correo a la persona",
            ),
        ),
    ]
