# Generated by Django 4.2.20 on 2026-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0053_relevamiento_avisos_correo_textos'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='identidad_forzada',
            field=models.BooleanField(default=False, verbose_name='Identidad validada manualmente'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='identidad_forzada_motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo de la validación manual'),
        ),
    ]
