# Generated by Django 4.2.20 on 2026-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0054_identidad_forzada'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaglobal',
            name='presentacion',
            field=models.CharField(blank=True, choices=[('LISTA', 'Lista de opciones'), ('BUSCADOR', 'Buscador con píldoras')], default='LISTA', help_text='Solo para Selector / Selector múltiple: cómo elige la persona entre las opciones.', max_length=20, verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='requisitonativo',
            name='presentacion',
            field=models.CharField(blank=True, choices=[('LISTA', 'Lista de opciones'), ('BUSCADOR', 'Buscador con píldoras')], default='LISTA', help_text='Solo para Selector / Selector múltiple: cómo elige la persona entre las opciones.', max_length=20, verbose_name='Presentación'),
        ),
    ]
