# Generated by Django 5.2.17 on 2026-09-06 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legajos", "0007_ampliar_uuid_legajos"),
        ("programas", "0056_padron_convocatoria_identidad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="formulario",
            index=models.Index(fields=["relevamiento", "creado"], name="prog_formulario_rel_creado_idx"),
        ),
    ]
