# Generated by Django 4.2.20 on 2026-08-30 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0057_catalogo_grupos_origen_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisenoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diseno', to='programas.convocatoria', verbose_name='Convocatoria')),
            ],
            options={
                'verbose_name': 'Diseño de formulario',
                'verbose_name_plural': 'Diseños de formulario',
            },
        ),
        migrations.CreateModel(
            name='ItemDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('grupo', 'Grupo'), ('campo', 'Campo'), ('texto', 'Texto')], max_length=10, verbose_name='Tipo de ítem')),
                ('clave', models.CharField(max_length=60, verbose_name='Clave')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('etiqueta', models.CharField(blank=True, max_length=240, verbose_name='Etiqueta')),
                ('subtitulo', models.CharField(blank=True, max_length=240, verbose_name='Subtítulo')),
                ('texto', models.TextField(blank=True, verbose_name='Texto')),
                ('condicion', models.JSONField(blank=True, null=True, verbose_name='Condición')),
                ('canal', models.CharField(choices=[('ambos', 'Ambos canales'), ('app', 'Solo app de campo'), ('link', 'Solo link público')], default='ambos', max_length=10, verbose_name='Se pide en')),
                ('propio', models.JSONField(blank=True, null=True, verbose_name='Campo propio')),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='programas.disenoformulario', verbose_name='Diseño')),
                ('grupo_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programas.gruporequisito', verbose_name='Grupo del catálogo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='programas.itemdiseno', verbose_name='Grupo contenedor')),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programas.preguntaglobal', verbose_name='Requisito general')),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programas.requisitonativo', verbose_name='Requisito nativo')),
            ],
            options={
                'verbose_name': 'Ítem del diseño',
                'verbose_name_plural': 'Ítems del diseño',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['diseno', 'padre', 'orden'], name='prog_item_diseno_orden_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='itemdiseno',
            constraint=models.UniqueConstraint(fields=('diseno', 'clave'), name='uniq_item_diseno_clave'),
        ),
    ]
