# Generated by Django 4.2.20 on 2026-09-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0057_formulario_indice_relevamiento_creado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['creado'], name='prog_formulario_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['validado_renaper', 'creado'], name='prog_formulario_renaper_idx'),
        ),
    ]
