# Generated by Django 4.2.20 on 2026-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0058_diseno_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='definicion',
            field=models.JSONField(blank=True, null=True, verbose_name='Foto de la definición'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='respuestas',
            field=models.JSONField(blank=True, default=dict, verbose_name='Respuestas por ítem'),
        ),
    ]
