# Generated by Django 5.2.17 on 2026-09-14 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0059_formulario_renaper_idx_con_relevamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='datos_siis',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos corregidos para SIIS'),
        ),
        migrations.AddField(
            model_name='preguntaglobal',
            name='destino_siis',
            field=models.CharField(blank=True, choices=[('prov_actual', 'Provincia del domicilio'), ('loc_actual', 'Localidad del domicilio'), ('barrio_actual', 'Barrio'), ('calle_altura', 'Calle y altura (piso, dpto)'), ('est_civil', 'Estado civil'), ('prov_nacim', 'Provincia de nacimiento'), ('loc_nacim', 'Localidad de nacimiento')], db_index=True, default='', help_text='Con qué campo del alta de beneficiarios en SIIS se corresponde la respuesta. Una sola pregunta activa por destino.', max_length=20, verbose_name='Este dato alimenta a SIIS como'),
        ),
        migrations.AddField(
            model_name='programasiis',
            name='siis_funcion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Función SIIS para el alta de beneficiarios'),
        ),
        migrations.AddField(
            model_name='programasiis',
            name='siis_funcion_nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre de la función SIIS'),
        ),
        migrations.CreateModel(
            name='EnvioSIIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('INCOMPLETO', 'Datos incompletos'), ('RECHAZADO', 'Rechazado por SIIS'), ('ERROR', 'Error técnico')], db_index=True, max_length=15)),
                ('siis_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID asignado por SIIS')),
                ('id_programa', models.PositiveIntegerField(blank=True, null=True)),
                ('id_funcion', models.PositiveIntegerField(blank=True, null=True)),
                ('documento', models.CharField(max_length=20)),
                ('codigo_error', models.CharField(blank=True, default='', max_length=40)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_sis', to='programas.formulario', verbose_name='Formulario')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_sis_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío a SIIS',
                'verbose_name_plural': 'Envíos a SIIS',
                'ordering': ['-creado'],
            },
        ),
    ]
