# Generated by Django 4.2.20 on 2026-08-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0060_sembrar_catalogo_protegido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validacionsis',
            options={'ordering': ['-creado', '-id'], 'verbose_name': 'Validación SIIS', 'verbose_name_plural': 'Validaciones SIIS'},
        ),
    ]
