# Generated by Django 4.2.20 on 2026-08-30 22:43

from django.db import migrations, models
import django.db.models.deletion
import programas.models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0061_orden_validacion_sis'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='padronhabilitado',
            name='uniq_padron_dni_convocatoria',
        ),
        migrations.AddField(
            model_name='padronhabilitado',
            name='relevamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padron_propio', to='programas.relevamiento', verbose_name='Relevamiento (padron propio)'),
        ),
        migrations.AddField(
            model_name='relevamiento',
            name='padron_archivo',
            field=models.FileField(blank=True, null=True, upload_to=programas.models.ruta_padron_becas, verbose_name='Padrón propio (Excel)'),
        ),
        migrations.AddIndex(
            model_name='padronhabilitado',
            index=models.Index(fields=['relevamiento', 'dni', 'sexo'], name='programas_padron_rel_dni_idx'),
        ),
        migrations.AddConstraint(
            model_name='padronhabilitado',
            constraint=models.UniqueConstraint(fields=('convocatoria', 'relevamiento', 'dni'), name='uniq_padron_dni_alcance'),
        ),
    ]
