# Generated by Django 4.2.20 on 2026-09-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0069_identificadores_siis_por_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinciaSiis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('siis_id', models.PositiveIntegerField(unique=True, verbose_name='Id. en SIIS')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre en SIIS')),
                ('clave', models.CharField(db_index=True, max_length=200, verbose_name='Clave de búsqueda')),
            ],
            options={
                'verbose_name': 'Provincia de SIIS',
                'verbose_name_plural': 'Provincias de SIIS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LocalidadSiis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('siis_id', models.PositiveIntegerField(verbose_name='Id. en SIIS (dentro de la provincia)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre en SIIS')),
                ('clave', models.CharField(db_index=True, max_length=200, verbose_name='Clave de búsqueda')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='programas.provinciasiis')),
            ],
            options={
                'verbose_name': 'Localidad de SIIS',
                'verbose_name_plural': 'Localidades de SIIS',
                'ordering': ['provincia__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AliasLocalidadSiis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(db_index=True, max_length=200, verbose_name='Clave del texto cargado')),
                ('texto', models.CharField(max_length=200, verbose_name='Tal como se cargó')),
                ('nota', models.CharField(blank=True, default='', max_length=300, verbose_name='Por qué')),
                ('localidad', models.ForeignKey(blank=True, help_text='Vacío: se revisó y no hay equivalencia; el caso se corrige a mano.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='programas.localidadsiis', verbose_name='Localidad de SIIS equivalente')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_localidades', to='programas.provinciasiis')),
            ],
            options={
                'verbose_name': 'Equivalencia de localidad',
                'verbose_name_plural': 'Equivalencias de localidad',
                'ordering': ['provincia__nombre', 'texto'],
            },
        ),
        migrations.AddConstraint(
            model_name='localidadsiis',
            constraint=models.UniqueConstraint(fields=('provincia', 'siis_id'), name='uniq_localidad_siis_provincia_id'),
        ),
        migrations.AddConstraint(
            model_name='aliaslocalidadsiis',
            constraint=models.UniqueConstraint(fields=('provincia', 'clave'), name='uniq_alias_localidad_provincia'),
        ),
    ]
