# Generated by Django 4.2.20 on 2026-09-21 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0070_catalogo_geografico_siis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaSiis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('total_pedido', models.PositiveIntegerField(verbose_name='Casos a procesar')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('TERMINADA', 'Terminada'), ('CANCELADA', 'Cancelada'), ('DETENIDA', 'Detenida')], db_index=True, default='EN_CURSO', max_length=12)),
                ('latido', models.DateTimeField(blank=True, null=True, verbose_name='Última señal de vida')),
                ('cancelacion_pedida', models.BooleanField(default=False, verbose_name='Se pidió frenar')),
                ('finalizada', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, default='', verbose_name='Por qué terminó')),
                ('mirados', models.PositiveIntegerField(default=0)),
                ('elegidos', models.PositiveIntegerField(default=0)),
                ('aprobados', models.PositiveIntegerField(default=0)),
                ('lista_espera', models.PositiveIntegerField(default=0)),
                ('altas', models.PositiveIntegerField(default=0)),
                ('incompletos', models.PositiveIntegerField(default=0)),
                ('rechazados', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas_siis', to='programas.programasiis')),
                ('solicitada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_siis_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corrida masiva a SIIS',
                'verbose_name_plural': 'Corridas masivas a SIIS',
                'ordering': ['-creado'],
            },
        ),
    ]
