# Generated by Django 4.2.20 on 2026-09-25 13:51
#
# Cambio 91: el DNI del titular pasa a una columna con índice. El chequeo de
# duplicado por convocatoria leía la clave ``dni`` del JSON de todos los
# formularios (sin índice, con el lock del relevamiento tomado) y bajo carga
# pasaba el read_timeout de 10 s de MySQL.

from django.db import migrations, models

LOTE = 1000


def poblar_dni_titular(apps, schema_editor):
    """Copia el DNI a la columna nueva: el del ciudadano vinculado o, si no
    hay, el de ``datos_identificacion``. Por lotes de pk para que ninguna
    consulta se acerque al read_timeout de producción."""
    Formulario = apps.get_model("programas", "Formulario")
    ultimo = 0
    while True:
        filas = list(
            Formulario.objects.filter(pk__gt=ultimo)
            .order_by("pk")
            .values_list("pk", "ciudadano__dni", "datos_identificacion")[:LOTE]
        )
        if not filas:
            break
        cambios = []
        for pk, dni_ciudadano, datos in filas:
            dni = dni_ciudadano or (datos.get("dni") if isinstance(datos, dict) else None) or ""
            dni = str(dni)[:20]
            if dni:
                cambios.append(Formulario(pk=pk, dni_titular=dni))
        if cambios:
            Formulario.objects.bulk_update(cambios, ["dni_titular"], batch_size=LOTE)
        ultimo = filas[-1][0]


class Migration(migrations.Migration):
    dependencies = [
        ("programas", "0071_corrida_siis"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="dni_titular",
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name="DNI del titular"),
        ),
        migrations.RunPython(poblar_dni_titular, migrations.RunPython.noop),
    ]
