# Generated by Django 5.2.17 on 2026-10-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0073_ampliar_relevamiento_token_publico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaIntermediaSIIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tdoc', models.PositiveSmallIntegerField(verbose_name='Tipo de documento')),
                ('dni', models.PositiveIntegerField(db_index=True)),
                ('cuil_pref', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cuil_dig', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apellido', models.CharField(blank=True, default='', max_length=50)),
                ('nombre', models.CharField(blank=True, default='', max_length=50)),
                ('sexo', models.CharField(blank=True, default='', max_length=1)),
                ('est_civil', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_nacim', models.DateField(blank=True, null=True)),
                ('prov_nacim', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('loc_nacim', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, default='', max_length=10)),
                ('correo_electron', models.CharField(blank=True, default='', max_length=50)),
                ('prov_actual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('loc_actual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('barrio_actual', models.CharField(blank=True, default='', max_length=50)),
                ('calle_actual', models.CharField(blank=True, default='', max_length=50)),
                ('nro_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('piso_actual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dpto_actual', models.CharField(blank=True, default='', max_length=50)),
                ('id_plan_soc', models.PositiveIntegerField(blank=True, null=True)),
                ('jurid', models.PositiveIntegerField(blank=True, null=True)),
                ('id_fun_x_plan', models.PositiveIntegerField(blank=True, null=True)),
                ('dni_apoderado', models.PositiveIntegerField(blank=True, null=True)),
                ('cuil_pref_apoderado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cuil_dig_apoderado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apellido_apoderado', models.CharField(blank=True, default='', max_length=50)),
                ('nombre_apoderado', models.CharField(blank=True, default='', max_length=50)),
                ('sexo_apoderado', models.CharField(blank=True, default='', max_length=1)),
                ('fecha_nacim_apoderado', models.DateField(blank=True, null=True)),
                ('sincronizado', models.BooleanField(db_index=True, default=False, verbose_name='Ya se informó a SIIS desde acá')),
                ('sincronizado_en', models.DateTimeField(blank=True, null=True)),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_intermedias', to='programas.enviosiis', verbose_name='Envío que la sincronizó')),
                ('formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alta_intermedia', to='programas.formulario', verbose_name='Formulario')),
                ('guardado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_intermedias_guardadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alta en la tabla intermedia',
                'verbose_name_plural': 'Altas en la tabla intermedia',
                'db_table': 'siis_tabla_intermedia',
                'ordering': ['-creado', '-pk'],
            },
        ),
    ]
