# Generated by Django 5.2.17 on 2026-10-07 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0078_adjunto_formulario_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncoordinador',
            name='fecha_asignacion',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='asignacionreferente',
            name='fecha_asignacion',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='asignacionterritorial',
            name='fecha_asignacion',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='inscripcionprograma',
            name='fecha_inscripcion',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Fecha de ingreso'),
        ),
    ]
