# Generated by Django 5.2.17 on 2026-10-08 20:07

import core.rutas_media
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('asunto', models.CharField(max_length=150, verbose_name='Asunto')),
                ('archivo_excel', models.FileField(max_length=255, upload_to=core.rutas_media.ruta_notificacion_excel, verbose_name='Lista de destinatarios (Excel)')),
                ('nombre_excel', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre original del Excel')),
                ('archivo_html', models.FileField(max_length=255, upload_to=core.rutas_media.ruta_notificacion_html, verbose_name='Cuerpo del correo (HTML)')),
                ('nombre_html', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre original del HTML')),
                ('html_sanitizado', models.TextField(blank=True, default='')),
                ('texto_plano', models.TextField(blank=True, default='')),
                ('elementos_quitados', models.PositiveIntegerField(default=0, verbose_name='Elementos inseguros quitados')),
                ('imagenes_no_visibles', models.PositiveIntegerField(default=0, verbose_name='Imágenes con ruta relativa o cid:')),
                ('estado', models.CharField(choices=[('A_ENVIAR', 'A enviar'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('ENVIADA_CON_ERRORES', 'Enviada con errores'), ('CANCELADA', 'Cancelada')], db_index=True, default='A_ENVIAR', max_length=20)),
                ('enviada_en', models.DateTimeField(blank=True, null=True, verbose_name='Envío iniciado')),
                ('finalizada_en', models.DateTimeField(blank=True, null=True, verbose_name='Envío terminado')),
                ('latido', models.DateTimeField(blank=True, null=True, verbose_name='Última señal de vida')),
                ('cancelacion_pedida', models.BooleanField(default=False, verbose_name='Se pidió detener')),
                ('mensaje', models.TextField(blank=True, default='', verbose_name='Último aviso del envío')),
                ('leidas', models.PositiveIntegerField(default=0, verbose_name='Filas leídas')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Destinatarios')),
                ('invalidos', models.PositiveIntegerField(default=0, verbose_name='Inválidos descartados')),
                ('duplicados', models.PositiveIntegerField(default=0, verbose_name='Duplicados descartados')),
                ('enviados', models.PositiveIntegerField(default=0)),
                ('fallidos', models.PositiveIntegerField(default=0)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_creadas', to=settings.AUTH_USER_MODEL)),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña de correo',
                'verbose_name_plural': 'Campañas de correo',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Descartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fila_excel', models.PositiveIntegerField(verbose_name='Fila del Excel')),
                ('valor', models.CharField(blank=True, default='', max_length=255, verbose_name='Valor leído')),
                ('motivo', models.CharField(choices=[('INVALIDO', 'Formato inválido'), ('DUPLICADO', 'Duplicado'), ('VACIO', 'Vacío')], max_length=10)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descartados', to='notificaciones.campana')),
            ],
            options={
                'verbose_name': 'Fila descartada',
                'verbose_name_plural': 'Filas descartadas',
                'ordering': ['fila_excel', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PruebaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=254)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='notificaciones.campana')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_de_campana', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba de campaña',
                'verbose_name_plural': 'Pruebas de campaña',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=254)),
                ('fila_excel', models.PositiveIntegerField(verbose_name='Fila del Excel')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=10)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='notificaciones.campana')),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'ordering': ['fila_excel', 'pk'],
                'indexes': [models.Index(fields=['campana', 'estado'], name='notif_dest_campana_estado'), models.Index(fields=['estado', 'enviado_en'], name='notif_dest_estado_enviado')],
                'constraints': [models.UniqueConstraint(fields=('campana', 'email'), name='notif_destinatario_unico')],
            },
        ),
    ]
