# Generated by Django 5.2.17 on 2026-10-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='corrida',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Corrida a cargo'),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'Enviándose'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=10),
        ),
    ]
