/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './templates/**/*.html',
    './**/templates/**/*.html',
    './static/custom/js/**/*.js',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        brand: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        xs: '12px', sm: '14px', base: '16px',
        lg: '18px', xl: '20px', '2xl': '24px', '3xl': '30px',
        '4xl': '36px', '5xl': '48px', '6xl': '60px',
      },
      borderRadius: {
        0: '0px', sm: '2px', DEFAULT: '4px', md: '6px',
        lg: '8px', xl: '12px', '2xl': '16px', '3xl': '24px', full: '9999px',
      },
      maxWidth: {
        xs: '320px', sm: '384px', md: '448px', lg: '512px',
        xl: '576px', '2xl': '672px', '3xl': '768px', '4xl': '896px',
        '5xl': '1024px', '6xl': '1152px', '7xl': '1280px',
      },
      colors: {
        magenta: 'var(--bg-pink)',
        'nodo-purple': 'var(--bg-brand)',
        'nodo-cyan': 'var(--bg-teal)',
        primario: 'var(--color-navy-900)',
        'primario-claro': 'var(--bg-brand)',
        'primario-oscuro': 'var(--color-navy-900)',
        secundario: 'var(--bg-brand)',
        'secundario-claro': 'var(--bg-teal)',
        'secundario-oscuro': 'var(--color-navy-900)',
        acento: 'var(--bg-pink)',
        'acento-claro': 'var(--bg-teal)',
        'acento-oscuro': 'var(--bg-olive)',
        primary: 'var(--color-navy-900)',
        secondary: 'var(--bg-brand)',
      },
      backgroundColor: {
        white: 'var(--bg-white)',
        'primary-soft': 'var(--bg-primary-soft)',
        secondary: 'var(--bg-secondary)',
        'secondary-soft': 'var(--bg-secondary-soft)',
        tertiary: 'var(--bg-tertiary)',
        quaternary: 'var(--bg-quaternary)',
        gray: 'var(--bg-gray)',
        brand: 'var(--bg-brand)',
        'brand-soft': 'var(--bg-brand-soft)',
        'brand-softer': 'var(--bg-brand-softer)',
        'brand-medium': 'var(--bg-brand-medium)',
        'brand-strong': 'var(--bg-brand-strong)',
        success: 'var(--bg-success)',
        'success-soft': 'var(--bg-success-soft)',
        danger: 'var(--bg-danger)',
        'danger-soft': 'var(--bg-danger-soft)',
        'danger-medium': 'var(--bg-danger-medium)',
        warning: 'var(--bg-warning)',
        'warning-soft': 'var(--bg-warning-soft)',
        'info-soft': 'var(--bg-info-soft)',
        dark: 'var(--bg-dark)',
        disabled: 'var(--bg-disabled)',
        pink: 'var(--bg-pink)',
      },
      textColor: {
        white: 'var(--text-white)',
        heading: 'var(--text-heading)',
        body: 'var(--text-body)',
        'body-subtle': 'var(--text-body-subtle)',
        'fg-brand': 'var(--text-fg-brand)',
        'fg-brand-subtle': 'var(--text-fg-brand-subtle)',
        'fg-brand-strong': 'var(--text-fg-brand-strong)',
        'fg-danger': 'var(--text-fg-danger)',
        'fg-danger-strong': 'var(--text-fg-danger-strong)',
        'fg-success': 'var(--text-fg-success)',
        'fg-warning': 'var(--text-fg-warning)',
        'fg-warning-subtle': 'var(--text-fg-warning-subtle)',
        'fg-disabled': 'var(--text-fg-disabled)',
        'fg-info': 'var(--text-fg-info)',
        pink: 'var(--text-fg-pink)',
      },
      borderColor: {
        base: 'var(--border-base)',
        'base-soft': 'var(--border-base-soft)',
        light: 'var(--border-light)',
        brand: 'var(--border-brand)',
        'brand-subtle': 'var(--border-brand-subtle)',
        'brand-light': 'var(--border-brand-light)',
        danger: 'var(--border-danger)',
        'danger-subtle': 'var(--border-danger-subtle)',
        success: 'var(--border-success)',
        'success-subtle': 'var(--border-success-subtle)',
        warning: 'var(--border-warning)',
        'warning-subtle': 'var(--border-warning-subtle)',
      },
    },
  },
  plugins: [],
};
