# Generated by Django 4.2.20 on 2026-06-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
