# Generated by Django 4.2.20 on 2026-06-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='ciudadano',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='derivado_por',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='inscripcion_creada',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='inscripcion_origen',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='programa_destino',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='programa_origen',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='respondido_por',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionprograma',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='ciudadano',
        ),
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='subsecretaria',
        ),
    ]
