# Generated by Django 4.2.20 on 2026-06-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        # Los índices sobre columnas que se eliminan deben quitarse ANTES del
        # RemoveField: MySQL los ajusta solo al dropear la columna, pero SQLite
        # (tests locales) reconstruye la tabla y falla si el estado conserva un
        # índice sobre un campo inexistente. Estos modelos se eliminan en 0003,
        # así que el estado posterior no cambia.
        migrations.RemoveIndex(
            model_name='derivacionprograma',
            name='legajos_der_ciudada_3ad38b_idx',
        ),
        migrations.RemoveIndex(
            model_name='derivacionprograma',
            name='legajos_der_program_ac3470_idx',
        ),
        migrations.RemoveIndex(
            model_name='inscripcionprograma',
            name='legajos_ins_ciudada_c9810b_idx',
        ),
        migrations.RemoveIndex(
            model_name='inscripcionprograma',
            name='legajos_ins_program_73dc01_idx',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='ciudadano',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='derivado_por',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='inscripcion_creada',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='inscripcion_origen',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='programa_destino',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='programa_origen',
        ),
        migrations.RemoveField(
            model_name='derivacionprograma',
            name='respondido_por',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionprograma',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='ciudadano',
        ),
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='subsecretaria',
        ),
    ]
