# Generated by Django 4.2.20 on 2026-06-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0002_remove_derivacionprograma_ciudadano_and_more'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivacion',
            name='actividad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones', to='programas.programa', verbose_name='Programa destino'),
        ),
        migrations.DeleteModel(
            name='DerivacionPrograma',
        ),
        migrations.DeleteModel(
            name='InscripcionPrograma',
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
    ]
