# Generated by Django 4.2.20 on 2026-06-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0003_alter_derivacion_actividad_destino_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Derivacion',
        ),
    ]
