# Generated by Django 4.2.20 on 2026-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0007_ampliar_uuid_legajos'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ciudadano',
            name='legajos_ciu_activo_b779fe_idx',
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['activo', 'apellido', 'nombre', 'dni', 'creado'], name='legajos_ciu_listado_idx'),
        ),
    ]
