# Generated by Django 5.2.17 on 2026-10-07 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0008_ciudadano_indice_listado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajoatencion',
            name='fecha_admision',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AlterField(
            model_name='legajoatencion',
            name='fecha_apertura',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
    ]
